server:
  servlet:
    context-path: /vishkode/v1
  port: 8081
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ems
    username: vishwanathr
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect